In [19]:
import pandas as pd

In [20]:
svi_df = pd.read_csv('../../data/data_sources/svi_2018_county.csv')
svi_df

,ST,STATE,ST_ABBR,COUNTY,FIPS,LOCATION,AREA_SQMI,E_TOTPOP,M_TOTPOP,E_HU,...,F_CROWD,F_NOVEH,F_GROUPQ,F_THEME4,F_TOTAL,E_UNINSUR,M_UNINSUR,EP_UNINSUR,MP_UNINSUR,E_DAYPOP
0,35,NEW MEXICO,NM,Rio Arriba,35039,"Rio Arriba County, New Mexico",5860.869195,39307,0,20044,...,0,0,0,1,-999,4160,588,10.6,1.5,32290
1,1,ALABAMA,AL,Autauga,1001,"Autauga County, Alabama",594.443459,55200,0,23315,...,0,0,0,0,0,3875,508,7.1,0.9,37301
2,1,ALABAMA,AL,Blount,1009,"Blount County, Alabama",644.830460,57645,0,24222,...,0,0,0,0,0,6303,732,11.0,1.3,40036
3,1,ALABAMA,AL,Butler,1013,"Butler County, Alabama",776.838201,20025,0,10026,...,0,0,0,0,0,2005,340,10.2,1.7,17280
4,1,ALABAMA,AL,Calhoun,1015,"Calhoun County, Alabama",605.867251,115098,0,53682,...,0,0,0,0,0,10686,796,9.4,0.7,117894
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3137,48,TEXAS,TX,Duval,48131,"Duval County, Texas",1793.476183,11355,0,5592,...,1,1,0,2,10,2656,406,24.5,3.7,9592
3138,48,TEXAS,TX,Zapata,48505,"Zapata County, Texas",998.411980,14369,0,6388,...,1,0,0,2,10,4206,484,29.3,3.4,10924
3139,48,TEXAS,TX,Zavala,48507,"Zavala County, Texas",1297.406535,12131,0,4344,...,1,1,0,2,10,2194,354,18.4,3.0,10672
3140,48,TEXAS,TX,Dimmit,48127,"Dimmit County, Texas",1328.884075,10663,0,4408,...,1,1,0,2,11,2345,539,22.2,5.1,8229
3141,48,TEXAS,TX,Jim Hogg,48247,"Jim Hogg County, Texas",1136.172598,5282,0,2523,...,1,1,0,2,11,988,262,18.8,5.0,4856

In [21]:
#drop unneeded columns
svi_df = svi_df.drop(columns = ['ST','STATE','ST_ABBR','COUNTY','LOCATION'])

In [22]:
svi_df = svi_df.set_index('FIPS')
svi_df.head()

,AREA_SQMI,E_TOTPOP,M_TOTPOP,E_HU,M_HU,E_HH,M_HH,E_POV,M_POV,E_UNEMP,...,F_CROWD,F_NOVEH,F_GROUPQ,F_THEME4,F_TOTAL,E_UNINSUR,M_UNINSUR,EP_UNINSUR,MP_UNINSUR,E_DAYPOP
FIPS,,,,,,,,,,,,,,,,,,,,,
35039,5860.869195,39307,0,20044,71,12398,439,-999,-999,-999,...,0,0,0,1,-999,4160,588,10.6,1.5,32290
1001,594.443459,55200,0,23315,71,21115,383,8422,1137,1065,...,0,0,0,0,0,3875,508,7.1,0.9,37301
1009,644.830460,57645,0,24222,55,20600,396,8220,992,909,...,0,0,0,0,0,6303,732,11.0,1.3,40036
1013,776.838201,20025,0,10026,51,6708,274,4640,521,567,...,0,0,0,0,0,2005,340,10.2,1.7,17280
1015,605.867251,115098,0,53682,184,45033,683,20819,1317,4628,...,0,0,0,0,0,10686,796,9.4,0.7,117894

In [23]:
#drop row with error - per data source documentation
svi_df = svi_df.drop(index = 35039)

In [24]:
base_col = svi_df[['AREA_SQMI','E_TOTPOP']]

In [25]:
#select all column names that start with an M - these are margin of error columns
cols = svi_df.columns.to_list()
col_series = pd.Series(cols)
moe_str = r'^M+.'
moe_form = col_series.str.contains(moe_str)
moe_col = col_series[moe_form].to_list()
flag_str = r'^F+.'
flag_form = col_series.str.contains(flag_str)
flag_col = col_series[flag_form].to_list()
pct_str = r'^[ERS]P+.'
pct_form = col_series.str.contains(pct_str)
pct_col = col_series[pct_form].to_list()
est_col = col_series[~pct_form & ~flag_form & ~moe_form]

In [26]:
# svi_E_df = svi_df[est_col]
# svi_E_df.to_csv('../../data/cleaned_data/svi_value_columns.csv')

In [27]:
# svi_F_df = svi_df[flag_col]
# # svi_FLAG_df = svi_FLAG_df.merge(svi_df[['AREA_SQMI','E_TOTPOP']], how = 'inner', left_index = True, right_index = True)
# svi_F_df.to_csv('../../data/cleaned_data/svi_flag_columns.csv')

In [29]:
svi_PCT_df = svi_df[pct_col]
svi_PCT_df = svi_PCT_df.merge(svi_df[['E_TOTPOP','AREA_SQMI']], how = 'inner', left_index=True, right_index = True)
svi_PCT_df

,EP_POV,EP_UNEMP,EP_PCI,EP_NOHSDP,EP_AGE65,EP_AGE17,EP_DISABL,EP_SNGPNT,EP_MINRTY,EP_LIMENG,...,EPL_CROWD,EPL_NOVEH,EPL_GROUPQ,SPL_THEME4,RPL_THEME4,SPL_THEMES,RPL_THEMES,EP_UNINSUR,E_TOTPOP,AREA_SQMI
FIPS,,,,,,,,,,,,,,,,,,,,,
1001,15.4,4.2,29372.0,11.3,14.6,24.2,19.3,7.5,25.0,0.8,...,0.2964,0.4846,0.1525,2.2760,0.3741,7.0688,0.4354,7.1,55200,594.443459
1009,14.4,4.1,22656.0,19.8,17.8,23.4,14.2,7.0,12.9,1.7,...,0.3703,0.2420,0.1165,1.7616,0.1741,7.0137,0.4242,11.0,57645,644.830460
1013,23.5,6.7,20430.0,15.4,19.0,22.8,17.7,10.5,48.1,0.5,...,0.4457,0.7685,0.3792,2.7290,0.6259,9.7579,0.8653,10.2,20025,776.838201
1015,18.6,8.8,24706.0,15.9,16.8,21.9,20.8,10.4,27.5,1.0,...,0.4056,0.5142,0.6250,2.7775,0.6492,9.4046,0.8252,9.4,115098,605.867251
1017,16.6,5.0,22827.0,18.6,18.9,20.7,16.7,9.7,44.2,0.1,...,0.7622,0.7224,0.3457,3.0735,0.7943,8.7787,0.7382,10.8,33826,596.560643
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48131,25.6,10.6,17864.0,32.9,17.8,26.1,26.2,15.8,90.9,5.7,...,0.9713,0.9074,0.7813,3.3299,0.8978,12.4228,0.9994,24.5,11355,1793.476183
48505,39.5,11.0,17228.0,40.0,13.9,33.6,17.3,17.1,95.7,24.4,...,0.9975,0.7794,0.0204,2.8683,0.6966,11.5737,0.9895,29.3,14369,998.411980
48507,34.8,8.4,13350.0,38.0,13.7,29.5,23.3,16.1,95.0,8.0,...,0.9414,0.9796,0.3792,3.4636,0.9331,12.2952,0.9987,18.4,12131,1297.406535
48127,29.8,16.4,18121.0,32.7,16.3,30.0,23.0,13.0,90.5,8.0,...,0.9809,0.9554,0.2184,3.4543,0.9316,12.4890,0.9997,22.2,10663,1328.884075
48247,27.4,11.5,17798.0,25.8,17.6,31.4,26.0,15.2,93.0,5.5,...,0.9736,0.9459,0.0436,2.5059,0.4919,11.6625,0.9917,18.8,5282,1136.172598

In [30]:
svi_PCT_df.to_csv('../../data/cleaned_data/svi_percent_columns.csv')