In [1]:
#import dependencies
import pandas as pd

In [2]:
#read in svi/socialcontext and case rate data
case_df = pd.read_csv('../modified_data/case_data.csv')
svi_cs_df = pd.read_csv('../modified_data/svi_social_context_merged')

In [3]:
#drio unneeded columns and set index for FIPS
case_df = case_df.drop('Unnamed: 0', axis=1)
case_df = case_df.set_index(case_df['FIPS'])
case_df = case_df.drop('FIPS', axis=1)
case_df

             Admin2 Province_State  3/31/21
FIPS
1001.0      Autauga        Alabama     6589
1003.0      Baldwin        Alabama    20505
1005.0      Barbour        Alabama     2227
1007.0         Bibb        Alabama     2542
1009.0       Blount        Alabama     6444
...             ...            ...      ...
56039.0       Teton        Wyoming     3609
56041.0       Uinta        Wyoming     2128
90056.0  Unassigned        Wyoming        0
56043.0    Washakie        Wyoming      891
56045.0      Weston        Wyoming      633

[3258 rows x 3 columns]

In [4]:
#Set index for FIPS
svi_cs_df = svi_cs_df.set_index(svi_cs_df['FIPS'])
svi_cs_df = svi_cs_df.drop(columns=['FIPS'])
svi_cs_df

,LOCATION,AREA_SQMI,E_TOTPOP,E_HU,E_HH,E_POV,E_UNEMP,E_PCI,E_NOHSDP,E_AGE65,...,Hopefulness,Income Mobility,Income Per Capita,Neuroticism,Openness,Religiosity,Risk Taking,Selflessness,Tolerance,Work Ethic
FIPS,,,,,,,,,,,,,,,,,,,,,
1001,"Autauga County, Alabama",594.443459,55200,23315,21115,8422,1065,29372,4204,8050,...,91.163142,-0.209446,26168.0,77.925476,78.222354,91.106719,53.333333,82.142857,70.000000,60.380952
1003,"Baldwin County, Alabama",1589.793007,208107,111945,78622,21653,4343,31203,14310,40665,...,82.484017,-0.118444,28069.0,77.232120,80.086368,71.771566,67.272980,75.586018,66.983549,70.972246
1005,"Barbour County, Alabama",885.001636,25782,11937,9186,6597,918,18461,4901,4634,...,61.927181,-0.593941,17249.0,80.375206,78.783778,73.657368,76.066481,78.753019,65.170377,68.704105
1007,"Bibb County, Alabama",622.461089,22527,9161,6840,2863,658,20199,2650,3661,...,85.258871,-0.198811,18988.0,80.813736,77.837027,69.974652,75.136154,76.929754,69.859503,67.931677
1009,"Blount County, Alabama",644.830460,57645,24222,20600,8220,909,22656,7861,10233,...,79.492703,0.298376,21033.0,78.764620,78.193105,92.045455,57.603815,79.307632,64.953288,76.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
56037,"Sweetwater County, Wyoming",10426.975725,44117,19628,15871,5237,1213,32624,2549,4721,...,82.403142,1.037294,30945.0,79.384759,79.347081,68.147062,73.938691,76.390464,67.420658,70.956334
56039,"Teton County, Wyoming",3996.844622,23059,13680,9158,1619,210,53703,958,3135,...,84.036899,0.665518,46499.0,71.547359,80.522872,65.399695,79.598153,79.698193,70.877600,70.938645
56041,"Uinta County, Wyoming",2081.719807,20609,8972,7735,2552,614,27009,934,2498,...,84.089095,0.939855,25636.0,78.771570,77.859042,67.603416,69.705859,73.332067,67.404487,69.299391
56043,"Washakie County, Wyoming",2238.672972,8129,3868,3422,984,253,27556,590,1686,...,87.485019,0.527082,26325.0,76.249370,77.658224,67.412774,82.820701,78.925326,74.628788,70.050103
56045,"Weston County, Wyoming",2398.003891,7100,3565,3062,1171,117,29152,389,1340,...,80.975991,1.315518,29493.0,79.961075,76.977099,71.535519,75.406846,76.730879,68.422269,69.413532

In [5]:
#merge files based on FIPS index
merged_df = case_df.merge(svi_cs_df, how='left', left_index=True, right_index=True)
merged_df

,Admin2,Province_State,3/31/21,LOCATION,AREA_SQMI,E_TOTPOP,E_HU,E_HH,E_POV,E_UNEMP,...,Hopefulness,Income Mobility,Income Per Capita,Neuroticism,Openness,Religiosity,Risk Taking,Selflessness,Tolerance,Work Ethic
FIPS,,,,,,,,,,,,,,,,,,,,,
1001.0,Autauga,Alabama,6589,"Autauga County, Alabama",594.443459,55200.0,23315.0,21115.0,8422.0,1065.0,...,91.163142,-0.209446,26168.0,77.925476,78.222354,91.106719,53.333333,82.142857,70.000000,60.380952
1003.0,Baldwin,Alabama,20505,"Baldwin County, Alabama",1589.793007,208107.0,111945.0,78622.0,21653.0,4343.0,...,82.484017,-0.118444,28069.0,77.232120,80.086368,71.771566,67.272980,75.586018,66.983549,70.972246
1005.0,Barbour,Alabama,2227,"Barbour County, Alabama",885.001636,25782.0,11937.0,9186.0,6597.0,918.0,...,61.927181,-0.593941,17249.0,80.375206,78.783778,73.657368,76.066481,78.753019,65.170377,68.704105
1007.0,Bibb,Alabama,2542,"Bibb County, Alabama",622.461089,22527.0,9161.0,6840.0,2863.0,658.0,...,85.258871,-0.198811,18988.0,80.813736,77.837027,69.974652,75.136154,76.929754,69.859503,67.931677
1009.0,Blount,Alabama,6444,"Blount County, Alabama",644.830460,57645.0,24222.0,20600.0,8220.0,909.0,...,79.492703,0.298376,21033.0,78.764620,78.193105,92.045455,57.603815,79.307632,64.953288,76.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NaN,Central Utah,Utah,8699,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Southeast Utah,Utah,3240,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Southwest Utah,Utah,27867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,TriCounty,Utah,3828,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
NaN,Weber-Morgan,Utah,28873,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
#check for nulls
merged_df.isnull().sum().to_list()

[2,
 0,
 0,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 117,
 177,
 177,
 177,
 177,
 177,
 177,
 177,
 180,
 177,
 177,
 177,
 442,
 177,
 177,
 177,
 177,
 177,
 177,
 177,
 177]

In [7]:
#drop column because of the large number of null values, drop rows with null values
cleaned_df = merged_df.drop('Income Mobility', axis=1)
cleaned_df = cleaned_df.dropna()
cleaned_df.columns.to_list()

['Admin2',
 'Province_State',
 '3/31/21',
 'LOCATION',
 'AREA_SQMI',
 'E_TOTPOP',
 'E_HU',
 'E_HH',
 'E_POV',
 'E_UNEMP',
 'E_PCI',
 'E_NOHSDP',
 'E_AGE65',
 'E_AGE17',
 'E_DISABL',
 'E_SNGPNT',
 'E_MINRTY',
 'E_LIMENG',
 'E_MUNIT',
 'E_MOBILE',
 'E_CROWD',
 'E_NOVEH',
 'E_GROUPQ',
 'EP_POV',
 'EP_UNEMP',
 'EP_PCI',
 'EP_NOHSDP',
 'EP_AGE65',
 'EP_AGE17',
 'EP_DISABL',
 'EP_SNGPNT',
 'EP_MINRTY',
 'EP_LIMENG',
 'EP_MUNIT',
 'EP_MOBILE',
 'EP_CROWD',
 'EP_NOVEH',
 'EP_GROUPQ',
 'EPL_POV',
 'EPL_UNEMP',
 'EPL_PCI',
 'EPL_NOHSDP',
 'SPL_THEME1',
 'RPL_THEME1',
 'EPL_AGE65',
 'EPL_AGE17',
 'EPL_DISABL',
 'EPL_SNGPNT',
 'SPL_THEME2',
 'RPL_THEME2',
 'EPL_MINRTY',
 'EPL_LIMENG',
 'SPL_THEME3',
 'RPL_THEME3',
 'EPL_MUNIT',
 'EPL_MOBILE',
 'EPL_CROWD',
 'EPL_NOVEH',
 'EPL_GROUPQ',
 'SPL_THEME4',
 'RPL_THEME4',
 'SPL_THEMES',
 'RPL_THEMES',
 'F_POV',
 'F_UNEMP',
 'F_PCI',
 'F_NOHSDP',
 'F_THEME1',
 'F_AGE65',
 'F_AGE17',
 'F_DISABL',
 'F_SNGPNT',
 'F_THEME2',
 'F_MINRTY',
 'F_LIMENG',
 'F_THEME3',
 'F_MUNIT',
 'F_MOBILE',
 'F_CROWD',
 'F_NOVEH',
 'F_GROUPQ',
 'F_THEME4',
 'F_TOTAL',
 'E_UNINSUR',
 'EP_UNINSUR',
 'E_DAYPOP',
 'Agreeableness',
 'Belief In Science',
 'Collectivism',
 'Conflict Awareness',
 'Conscientiousness',
 'Empathy',
 'Employment Rate',
 'Entrepreneurship',
 'Extraversion',
 'Gender Equality',
 'Hopefulness',
 'Income Per Capita',
 'Neuroticism',
 'Openness',
 'Religiosity',
 'Risk Taking',
 'Selflessness',
 'Tolerance',
 'Work Ethic']

In [8]:
#drop unneeded columns
cleaned_df = cleaned_df.drop(columns=['Admin2','Province_State','LOCATION'])

In [9]:
cleaned_df.dtypes.to_list()

[dtype('int64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64'),
 dtype('float64')]

In [10]:
#write to CSV
cleaned_df.to_csv('../modified_data/merged_cleaned.csv')