In [1]:
import pandas as pd
from sqlalchemy import create_engine
from config import db_password
import psycopg2

In [33]:
#create engine and connect to AWS RDS
db_string = f"postgresql://postgres:{db_password}@capstone-db.cutxgn80t57o.us-west-1.rds.amazonaws.com"
engine = create_engine(db_string)

In [39]:
deaths_df = pd.read_sql('deaths_merged_full', con = engine)
deaths_df

,FIPS,AREA_SQMI,E_TOTPOP,E_HU,E_HH,E_POV,E_UNEMP,E_PCI,E_NOHSDP,E_AGE65,...,Gender Equality,Hopefulness,Income Per Capita,Neuroticism,Openness,Religiosity,Risk Taking,Selflessness,Tolerance,Work Ethic
0,1001,594.443459,55200,23315,21115,8422,1065,29372,4204,8050,...,77.063492,91.163142,26168.0,77.925476,78.222354,91.106719,53.333333,82.142857,70.000000,60.380952
1,1009,644.830460,57645,24222,20600,8220,909,22656,7861,10233,...,64.585114,79.492703,21033.0,78.764620,78.193105,92.045455,57.603815,79.307632,64.953288,76.000000
2,1013,776.838201,20025,10026,6708,4640,567,20430,2141,3806,...,64.769089,83.523765,19011.0,78.563680,76.109761,76.623924,69.058104,79.956648,67.920284,72.773953
3,1015,605.867251,115098,53682,45033,20819,4628,24706,12620,19386,...,69.015332,83.365608,22231.0,79.439032,79.955121,77.918741,54.063568,76.745724,67.456150,68.292794
4,1017,596.560643,33826,16981,13516,5531,773,22827,4383,6409,...,69.433309,85.371517,21532.0,76.995358,78.156771,75.891100,67.343775,79.128558,66.397785,69.554441
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3053,48229,4570.523160,4098,1562,900,951,101,14190,1263,639,...,67.196038,55.568966,14776.0,76.720396,79.603081,73.986415,70.917126,79.605796,75.878105,71.008448
3054,48131,1793.476183,11355,5592,3511,2751,482,17864,2386,2025,...,66.171080,77.899678,19853.0,79.125428,78.895880,76.629575,60.576045,73.670302,64.571017,68.007770
3055,48505,998.411980,14369,6388,4405,5609,621,17228,3226,1999,...,67.037410,86.586509,16007.0,79.355639,79.572483,74.378252,77.443239,76.386871,74.001471,73.609838
3056,48507,1297.406535,12131,4344,3509,4150,421,13350,2719,1665,...,65.804541,88.785822,13393.0,78.392216,76.024682,75.848196,76.967659,77.303576,70.010162,71.121990
3057,48247,1136.172598,5282,2523,1710,1431,229,17798,812,932,...,68.661277,82.727613,16637.0,80.157542,79.708963,74.399849,74.024835,77.564505,72.456881,70.160988

In [40]:
cases_df = pd.read_sql('cases_merged_full', con = engine)
cases_df

,FIPS,AREA_SQMI,E_TOTPOP,E_HU,E_HH,E_POV,E_UNEMP,E_PCI,E_NOHSDP,E_AGE65,...,Hopefulness,Income Per Capita,Neuroticism,Openness,Religiosity,Risk Taking,Selflessness,Tolerance,Work Ethic,First_yr_cases
0,1001,594.443459,55200,23315,21115,8422,1065,29372,4204,8050,...,91.163142,26168.0,77.925476,78.222354,91.106719,53.333333,82.142857,70.000000,60.380952,6589
1,1009,644.830460,57645,24222,20600,8220,909,22656,7861,10233,...,79.492703,21033.0,78.764620,78.193105,92.045455,57.603815,79.307632,64.953288,76.000000,6444
2,1013,776.838201,20025,10026,6708,4640,567,20430,2141,3806,...,83.523765,19011.0,78.563680,76.109761,76.623924,69.058104,79.956648,67.920284,72.773953,2097
3,1015,605.867251,115098,53682,45033,20819,4628,24706,12620,19386,...,83.365608,22231.0,79.439032,79.955121,77.918741,54.063568,76.745724,67.456150,68.292794,14224
4,1017,596.560643,33826,16981,13516,5531,773,22827,4383,6409,...,85.371517,21532.0,76.995358,78.156771,75.891100,67.343775,79.128558,66.397785,69.554441,3488
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3053,48229,4570.523160,4098,1562,900,951,101,14190,1263,639,...,55.568966,14776.0,76.720396,79.603081,73.986415,70.917126,79.605796,75.878105,71.008448,512
3054,48131,1793.476183,11355,5592,3511,2751,482,17864,2386,2025,...,77.899678,19853.0,79.125428,78.895880,76.629575,60.576045,73.670302,64.571017,68.007770,1214
3055,48505,998.411980,14369,6388,4405,5609,621,17228,3226,1999,...,86.586509,16007.0,79.355639,79.572483,74.378252,77.443239,76.386871,74.001471,73.609838,1760
3056,48507,1297.406535,12131,4344,3509,4150,421,13350,2719,1665,...,88.785822,13393.0,78.392216,76.024682,75.848196,76.967659,77.303576,70.010162,71.121990,1844
3057,48247,1136.172598,5282,2523,1710,1431,229,17798,812,932,...,82.727613,16637.0,80.157542,79.708963,74.399849,74.024835,77.564505,72.456881,70.160988,605