In [1]:
import pandas as pd
from sqlalchemy import create_engine
from config import db_password
import psycopg2

In [2]:
#create engine and connect to AWS RDS
db_string = f"postgresql://postgres:{db_password}@capstone-db.cutxgn80t57o.us-west-1.rds.amazonaws.com"
engine = create_engine(db_string)

In [3]:
# read and check merged death table
deaths_df = pd.read_sql('deaths_merged_full', con = engine)
deaths_df

,FIPS,AREA_SQMI,E_TOTPOP,E_HU,E_HH,E_POV,E_UNEMP,E_PCI,E_NOHSDP,E_AGE65,...,Gender Equality,Hopefulness,Income Per Capita,Neuroticism,Openness,Religiosity,Risk Taking,Selflessness,Tolerance,Work Ethic
0,1001,594.443459,55200,23315,21115,8422,1065,29372,4204,8050,...,77.063492,91.163142,26168.0,77.925476,78.222354,91.106719,53.333333,82.142857,70.000000,60.380952
1,1009,644.830460,57645,24222,20600,8220,909,22656,7861,10233,...,64.585114,79.492703,21033.0,78.764620,78.193105,92.045455,57.603815,79.307632,64.953288,76.000000
2,1013,776.838201,20025,10026,6708,4640,567,20430,2141,3806,...,64.769089,83.523765,19011.0,78.563680,76.109761,76.623924,69.058104,79.956648,67.920284,72.773953
3,1015,605.867251,115098,53682,45033,20819,4628,24706,12620,19386,...,69.015332,83.365608,22231.0,79.439032,79.955121,77.918741,54.063568,76.745724,67.456150,68.292794
4,1017,596.560643,33826,16981,13516,5531,773,22827,4383,6409,...,69.433309,85.371517,21532.0,76.995358,78.156771,75.891100,67.343775,79.128558,66.397785,69.554441
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3053,48229,4570.523160,4098,1562,900,951,101,14190,1263,639,...,67.196038,55.568966,14776.0,76.720396,79.603081,73.986415,70.917126,79.605796,75.878105,71.008448
3054,48131,1793.476183,11355,5592,3511,2751,482,17864,2386,2025,...,66.171080,77.899678,19853.0,79.125428,78.895880,76.629575,60.576045,73.670302,64.571017,68.007770
3055,48505,998.411980,14369,6388,4405,5609,621,17228,3226,1999,...,67.037410,86.586509,16007.0,79.355639,79.572483,74.378252,77.443239,76.386871,74.001471,73.609838
3056,48507,1297.406535,12131,4344,3509,4150,421,13350,2719,1665,...,65.804541,88.785822,13393.0,78.392216,76.024682,75.848196,76.967659,77.303576,70.010162,71.121990
3057,48247,1136.172598,5282,2523,1710,1431,229,17798,812,932,...,68.661277,82.727613,16637.0,80.157542,79.708963,74.399849,74.024835,77.564505,72.456881,70.160988

In [4]:
# read and check merged cases table
cases_df = pd.read_sql('cases_merged_full', con = engine)
cases_df

,FIPS,AREA_SQMI,E_TOTPOP,E_HU,E_HH,E_POV,E_UNEMP,E_PCI,E_NOHSDP,E_AGE65,...,Hopefulness,Income Per Capita,Neuroticism,Openness,Religiosity,Risk Taking,Selflessness,Tolerance,Work Ethic,first_yr_cases
0,1001,594.443459,55200,23315,21115,8422,1065,29372,4204,8050,...,91.163142,26168.0,77.925476,78.222354,91.106719,53.333333,82.142857,70.000000,60.380952,6589
1,1009,644.830460,57645,24222,20600,8220,909,22656,7861,10233,...,79.492703,21033.0,78.764620,78.193105,92.045455,57.603815,79.307632,64.953288,76.000000,6444
2,1013,776.838201,20025,10026,6708,4640,567,20430,2141,3806,...,83.523765,19011.0,78.563680,76.109761,76.623924,69.058104,79.956648,67.920284,72.773953,2097
3,1015,605.867251,115098,53682,45033,20819,4628,24706,12620,19386,...,83.365608,22231.0,79.439032,79.955121,77.918741,54.063568,76.745724,67.456150,68.292794,14224
4,1017,596.560643,33826,16981,13516,5531,773,22827,4383,6409,...,85.371517,21532.0,76.995358,78.156771,75.891100,67.343775,79.128558,66.397785,69.554441,3488
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3053,48229,4570.523160,4098,1562,900,951,101,14190,1263,639,...,55.568966,14776.0,76.720396,79.603081,73.986415,70.917126,79.605796,75.878105,71.008448,512
3054,48131,1793.476183,11355,5592,3511,2751,482,17864,2386,2025,...,77.899678,19853.0,79.125428,78.895880,76.629575,60.576045,73.670302,64.571017,68.007770,1214
3055,48505,998.411980,14369,6388,4405,5609,621,17228,3226,1999,...,86.586509,16007.0,79.355639,79.572483,74.378252,77.443239,76.386871,74.001471,73.609838,1760
3056,48507,1297.406535,12131,4344,3509,4150,421,13350,2719,1665,...,88.785822,13393.0,78.392216,76.024682,75.848196,76.967659,77.303576,70.010162,71.121990,1844
3057,48247,1136.172598,5282,2523,1710,1431,229,17798,812,932,...,82.727613,16637.0,80.157542,79.708963,74.399849,74.024835,77.564505,72.456881,70.160988,605

In [14]:
cre_df = pd.read_sql('cre_cases_county', con = engine)
cre_df

,FIPS,Agreeableness,Belief In Science,Collectivism,Conflict Awareness,Conscientiousness,Empathy,Employment Rate,Entrepreneurship,Extraversion,...,Tolerance,Work Ethic,POPUNI,PRED0_PE,PRED12_PE,PRED3_PE,dem_pct,num_beds,AREA_SQMI,first_yr_cases
0,1001,86.279655,70.833333,57.142857,63.444323,84.113820,83.308726,94.7,12.968300,86.112526,...,70.000000,60.380952,55688,36.94,40.85,22.20,27.018365,85.0,594.443459,6589
1,1003,85.603337,63.268161,67.948815,63.751017,83.108459,78.187835,94.6,13.748191,87.033806,...,66.983549,70.972246,221898,35.43,40.81,23.76,22.409030,332.0,1589.793007,20505
2,1005,87.711609,63.046939,70.099756,51.165707,83.933892,81.289184,91.4,13.026820,86.056212,...,65.170377,68.704105,22023,22.81,41.64,35.54,45.788173,74.0,885.001636,2227
3,1007,84.830261,63.262028,72.034797,61.796095,82.099210,81.212388,93.4,6.984127,85.527388,...,69.859503,67.931677,20393,30.79,44.06,25.14,20.698280,35.0,622.461089,2542
4,1009,85.548096,33.333333,80.000000,63.136502,83.165976,81.521844,94.5,11.572700,87.164757,...,64.953288,76.000000,57697,31.53,41.51,26.97,9.569378,40.0,644.830460,6444
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3053,55061,86.977808,69.740482,67.600256,59.029269,83.032529,80.145155,96.2,8.444444,87.027840,...,73.203803,72.306047,20412,45.63,36.17,18.20,32.873088,0.0,342.453886,2611
3054,55077,82.373940,64.358836,64.461951,67.245194,80.150093,81.429034,94.8,10.738255,87.881433,...,61.340226,74.180817,15536,35.10,40.70,24.20,35.730833,0.0,455.706769,1509
3055,55078,82.225702,64.624248,70.834632,43.086886,80.039129,76.122630,92.2,7.228916,86.455125,...,68.229703,72.254198,4516,20.04,41.98,37.98,81.949686,0.0,357.614455,797
3056,55093,86.462071,73.863636,66.666667,59.359781,82.730282,80.634657,95.8,10.215827,89.816151,...,55.937500,64.000000,40243,45.17,39.57,15.26,42.012266,0.0,573.852683,4547
3057,56035,81.705081,68.291494,67.326703,58.547384,80.643211,81.243327,93.6,13.513514,87.061551,...,71.208097,66.680314,9813,33.97,44.11,21.92,17.640000,0.0,4886.479501,705

In [53]:
deaths_df = pd.read_sql('cre_deaths_county', con = engine)

POPUNI                  int64
PRED0_PE              float64
PRED12_PE             float64
PRED3_PE              float64
num_beds              float64
dem_pct               float64
FIPS                    int64
Agreeableness         float64
Belief In Science     float64
Collectivism          float64
Conflict Awareness    float64
Conscientiousness     float64
Empathy               float64
Employment Rate       float64
Entrepreneurship      float64
Extraversion          float64
Gender Equality       float64
Hopefulness           float64
Income Per Capita     float64
Neuroticism           float64
Openness              float64
Religiosity           float64
Risk Taking           float64
Selflessness          float64
Tolerance             float64
Work Ethic            float64
AREA_SQMI             float64
first_yr_deaths         int64
dtype: object